use_frameworks!

platform :ios, '10.0'

target 'CFYNetworking_Example' do
  pod 'CFYNetworking', :path => '../'

  target 'CFYNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
